language: java
jdk: oraclejdk8
script:
  - ./mvnw clean install -B
  - ./mvnw spring-boot:run -B
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  skip_cleanup: true
  api-key: $HEROKU_API_KEY