language: java
jdk: oraclejdk8
script:
  - ./mvnw clean install -B
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  skip_cleanup: true
  api-key:
   secure: $HEROKU_API_KEY
  app: vendinspr
